### ISSUE TITLE
Support for scale = 0.003?

### ISSUE THREAD

**Issue by renyuneyun** [SolidBench/SolidBench.js#1]
I'm using this tool (with https://github.com/SolidLabResearch/css-populate) to generate data for benchmarking CSS. The default setting works correctly for me.

But during testing, I often found the data too large. I then found https://github.com/ldbc/ldbc_snb_datagen_spark/pull/146 which added another scale factor (`scale`) value `0.003`.
But when trying to use `0.003` on this tool, it fails. After manually modifying `CommandGenerate` to accept this value as argument, it still fails.
Is there a way to make it work?

**Comment by rubensworks** [comment]
LDBC SNB unfortunately stopped supporting Turtle as output (https://github.com/ldbc/ldbc_snb_datagen_spark/issues/228). So we're using an older version of their generator, which does not seem to include that scale factor yet.

So there's no way to make this work I'm afraid, for this we'd need Turtle support in LDBC SNB.

**Comment by renyuneyun** [comment]
I see. That's unfortunate...

Do you have any suggestions on where I should look to find information on (controlling) the output format for LDBC generator?

**Comment by rubensworks** [comment]
This is the place I think: https://github.com/ldbc/ldbc_snb_datagen_spark

One option is to create an issue on that issue tracker to ask for help.
