### ISSUE TITLE
Tags do not generate correct type relations.

### ISSUE THREAD

**Issue by jitsedesmet** [SolidBench/SolidBench.js#9]
The diagram in the readme suggests tags have a `hasType` relation, this is not true. The snb dataset uses `rdf:type` to model this relationship instead, I suggest we update the diagram to be consistent (`rdf:type` relationships are visualized with white arrows?)

![image](https://github.com/SolidBench/SolidBench.js/assets/35114273/38ce01ca-5cbe-468e-abd1-b6604a3019fa)

Additionally tags are not generated correctly, right now a tag document looks like this:
```nt
<http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/tag/Chloe_Dancer/Crown_of_Thorns> <http://xmlns.com/foaf/0.1/name> "Chloe_Dancer/Crown_of_Thorns" .
<http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/tag/Chloe_Dancer/Crown_of_Thorns> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:b0_tagclass000180 .
<http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/tag/Chloe_Dancer/Crown_of_Thorns> <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/id> "15517"^^<http://www.w3.org/2001/XMLSchema#int> .
```
Note that the type is a blanknode, but the blank node is not further defined.

The original dataset has the following info:
```ttl
<http://www.ldbc.eu/ldbc_socialnet/1.0/tag/Hamid_Karzai> foaf:name "Hamid_Karzai" .
<http://www.ldbc.eu/ldbc_socialnet/1.0/tag/Hamid_Karzai> rdf:type _:tagclass000349 .
<http://www.ldbc.eu/ldbc_socialnet/1.0/tag/Hamid_Karzai> snvoc:id "0"^^xsd:int .
_:tagclass000349 rdfs:label "OfficeHolder" .
_:tagclass000349 rdf:type snvoc:TagClass .
_:tagclass000349 snvoc:url dbpedia-owl:OfficeHolder .
_:tagclass000349 snvoc:id "349"^^xsd:int .
_:tagclass000349 rdfs:subClassOf _:tagclass000211 .
```
So there is additional information provided regarding the blankNode. We should also implement this and provide the blank nodes as resources.

**Comment by rubensworks** [comment]
Regarding the diagram; it's provided by [LDBC](https://github.com/ldbc/ldbc_snb_datagen_hadoop), and is format-agnostic. So it may not fully correspond to RDF.

If we want to modify the schema, we'll have to start from scratch (which is possible, but will require a big effort).

**Comment by jitsedesmet** [comment]
I don't think it's worth the effort. I think the schema wants to capture more of the "semantics" and shouldn't be seen as a literal visualization of the data.
